auto commit by j842/build

diff --git a/drunner/servicerunner b/drunner/servicerunner
--- a/drunner/servicerunner
+++ b/drunner/servicerunner
@@ -121,6 +121,9 @@ function main {
             ;;
          
          selftest)
+            echo "I just failed! -- stdout"
+            echo "I just failed! -- stderr"
+            exit 1
             ;;
             
          #--- custom commands
