Working on tests.

diff --git a/drunner/test b/drunner/test
--- a/drunner/test
+++ b/drunner/test
@@ -1,14 +1,24 @@
 #!/bin/bash
+set -o nounset
 source "$( dirname "$(readlink -f "$0")" )/_variables"
 
 # This script is run on the host.
 # It launches the docker container and runs our hello world command.
 
 function passfailmsg {
-   if [ $2 -eq 0 ]; then
-      echo -e "[ \e[32m\u2714\e[0m ] $1" >&2
+   PFMSG="$1"
+   
+   echo -e "[ \e[2m?\e[0m ] $PFMSG">&2   
+}
+
+function passfail {
+   # go up a line
+   echo -en "\e[1A">&2
+   # rewrite
+   if [ $1 -eq 0 ]; then
+      echo -e "[ \e[32m\u2714\e[0m ] $PFMSG" >&2
    else
-      echo -e "[ \e[31m\e[1m\u2718\e[0m ] $1" >&2
+      echo -e "[ \e[31m\e[1m\u2718\e[0m ] $PFMSG" >&2
    fi
 }
 
@@ -27,14 +37,49 @@ function testdrunner {
    local IMAGENAME="$1"
 
    title "Testing $IMAGENAME"
+   
+   local SERVICE="test-${IMAGENAME//[![:alnum:]]/}"
+   
+   passfailmsg "create tempdir"
+   local TEMPDIR="$(mktemp -d)"
+   PFMSG="create tempdir ${TEMPDIR}" ; passfail $?
+   
+   ( #subshell, so if we exit we still clean up
+      passfailmsg "drunner install ${IMAGENAME} ${SERVICE}"
+      drunner install "${IMAGENAME}" "${SERVICE}" >/dev/null 2>&1
+      passfail $?
+      
+      passfailmsg "drunner update ${SERVICE}"
+      drunner update "${SERVICE}" >/dev/null 2>&1
+      passfail $?
+      
+      passfailmsg "drunner enter ${SERVICE} -c \"echo hi\""
+      drunner enter "${SERVICE}" -c "echo hi" >/dev/null 2>&1
+      passfail $?      
+           
+      local PASS="password123"
+      passfailmsg "PASS=${PASS} drunner backup ${SERVICE} ${TEMPDIR}/backup"
+      bash -c "PASS=${PASS} drunner backup ${SERVICE} ${TEMPDIR}/backup"
+      passfail $?
+   )
 
-   passfailmsg "Testing $CONTAINER" 0
-   passfailmsg "Testing $CONTAINER" 1
+   passfailmsg "drunner destroy ${SERVICE}-clone"
+   drunner destroy "${SERVICE}-clone" >/dev/null 2>&1
+   passfail $?      
 
+   passfailmsg "drunner destroy ${SERVICE}"
+   drunner destroy "${SERVICE}" >/dev/null 2>&1
+   passfail $?      
+   
+   passfailmsg "remove ${TEMPDIR}"
+   rm -r ${TEMPDIR}
+   passfail $?
+   
    echo " ">&2
 }
 
 
+RVAL=0
 testdrunner ${1:-"drunner/test"}
 
 
